name: deen_stream
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cached_network_image: null
  cupertino_icons: ^1.0.8
  curved_labeled_navigation_bar: ^2.0.6
  flutter:
    sdk: flutter
  googleapis: ^13.0.0
  googleapis_auth: ^1.6.0
  http: ^1.6.0
  infinite_scroll_pagination: null
  visibility_detector: ^0.4.0+2
  youtube_player_flutter: ^9.1.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.3

icons_launcher:
  image_path: "assets/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true

  assets:
    - assets/
